Create stop loss.md
demiculus/mentalmodel pull request #9
Opened 2020-11-02 14:05 UTC by equinimox

2020-11-02 14:09 UTC, demiculus requested changes
I'll approve pr with these included

2020-11-02 14:09 UTC, demiculus commented on _mental_models/stop loss.md
> +summary: Letting go becomes harder with more Investing
> Letting go becomes harder with more Investing

Change investing to exposure

2020-11-02 14:09 UTC, demiculus commented on _mental_models/stop loss.md
> +Coming Soon.
Handle description

2020-11-02 14:09 UTC, demiculus commented on _mental_models/stop loss.md
> +Coming Soon.
Handle practice

2020-11-02 14:09 UTC, demiculus commented on _mental_models/stop loss.md
> +#### [Example-1]
Create at least 2 examples

2022-05-28 16:46 UTC, goktugyil commented
status?

2022-05-29 10:01 UTC, demiculus commented
@equinimox

2022-05-29 12:23 UTC, equinimox commented
I'm not interested in completing the article, i see no incentive for the
work or website.

summary:
1. evaluate importance of the problem for yourself.

2. ask yourself what you can afford to lose consciously in different
layers: emotional, psychological, financial, health&relationship wise???

3. try to create exit strategies. choose whether going cold turkey or
gradually would be better. how risky is the problem; should you go
pessimistic or optimistic.
use other mm's like second order thinking, prerequisites

4. create reminders for the exit somehow (calendar event, alarm, friend,
reminding object)


On Sun, May 29, 2022, 13:01 Demi Yilmaz ***@***.***> wrote:

> @equinimox <https://github.com/equinimox>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/demiculus/mentalmodel/pull/9#issuecomment-1140415810>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE2ZNIX6VVBZZ73OTMPXZ5DVMM565ANCNFSM4THQHI4Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-13 03:44 UTC, closed without merging